project_id = "kwwzfhpamciilgmknsov"

[functions.news-agent]
verify_jwt = false

[functions.rewrite-article]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.chat]
verify_jwt = false
